In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


Load Dataset SVHN_single_grey1.h5

In [0]:
import h5py
import numpy as np

SVHN=h5py.File('/content/drive/My Drive/Colab Notebooks/SVHN_single_grey1.h5','r')

#Load training and Test data

x_train=SVHN['X_train'][:]
y_train=SVHN['y_train'][:]
x_test=SVHN['X_test'][:]
y_test=SVHN['y_test'][:]
x_val = SVHN['X_val'][:]
y_val = SVHN['y_val'][:]

#Close File
SVHN.close()

In [5]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(42000, 32, 32)
(18000, 32, 32)
(42000,)
(18000,)


In [0]:
#Reshape Data for KNN
x_train1=x_train.reshape(x_train.shape[0],32*32)
x_test1=x_test.reshape(x_test.shape[0],32*32)

In [9]:
#Applyig KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

knn= KNeighborsClassifier()
knn.fit(x_train1,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
#Prediction
y_pred = knn.predict(x_test1)

In [11]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.49016666666666664
              precision    recall  f1-score   support

           0       0.38      0.66      0.48      1814
           1       0.44      0.70      0.54      1828
           2       0.55      0.52      0.53      1803
           3       0.42      0.39      0.41      1719
           4       0.67      0.61      0.64      1812
           5       0.48      0.36      0.41      1768
           6       0.47      0.38      0.42      1832
           7       0.72      0.58      0.64      1808
           8       0.42      0.33      0.37      1812
           9       0.52      0.36      0.43      1804

    accuracy                           0.49     18000
   macro avg       0.51      0.49      0.49     18000
weighted avg       0.51      0.49      0.49     18000

[[1201   60   44   37   45   45  129   31  109  113]
 [ 125 1285   83   81   84   36   36   58   18   22]
 [ 126  252  932  115   44   44   28  128   69   65]
 [ 164  255  166  677   54  157   36   46   92   72]
 [ 148  2

In [12]:
#Using Neural networks

import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
y_train=keras.utils.to_categorical(y_train,10)
y_test=keras.utils.to_categorical(y_test,10)
y_val=keras.utils.to_categorical(y_val,10)

In [0]:
x_train2=x_train.reshape(x_train.shape[0],32,32,1).astype('float32')
x_test2=x_test.reshape(x_test.shape[0],32,32,1).astype('float32')
x_val2=x_val.reshape(x_val.shape[0],32,32,1).astype('float32')

In [0]:
#Normalizing the data
x_train2/=255
x_test2/=255
x_val2/=255

In [16]:
#Building Model
model=Sequential()
model.add(keras.layers.Flatten(input_shape=(32,32,1)))
model.add(Dense(200,activation ='relu'))
model.add(Dense(100,activation ='relu'))
model.add(keras.layers.Dropout(0.25))
model.add(Dense(10,activation='softmax'))

W0730 18:16:20.067854 140060881422208 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0730 18:16:20.110186 140060881422208 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0730 18:16:20.130434 140060881422208 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0730 18:16:20.155614 140060881422208 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0730 18:16:20.163493 

In [17]:
#Compile
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

W0730 18:16:50.922676 140060881422208 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0730 18:16:50.951926 140060881422208 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [18]:
model.fit(x_train2,y_train, batch_size=64, epochs=10, 
              validation_data=(x_test2, y_test))

W0730 18:17:00.117035 140060881422208 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 42000 samples, validate on 18000 samples
Epoch 1/10
42000/42000 [==============================] - 6s 154us/step - loss: 2.2872 - acc: 0.1424 - val_loss: 2.2563 - val_acc: 0.1969
Epoch 2/10
42000/42000 [==============================] - 2s 56us/step - loss: 2.2242 - acc: 0.2258 - val_loss: 2.1695 - val_acc: 0.3302
Epoch 3/10
42000/42000 [==============================] - 2s 56us/step - loss: 2.1184 - acc: 0.2931 - val_loss: 2.0270 - val_acc: 0.3919
Epoch 4/10
42000/42000 [==============================] - 2s 56us/step - loss: 1.9595 - acc: 0.3608 - val_loss: 1.8426 - val_acc: 0.4292
Epoch 5/10
42000/42000 [==============================] - 2s 56us/step - loss: 1.7952 - acc: 0.4183 - val_loss: 1.6997 - val_acc: 0.4791
Epoch 6/10
42000/42000 [==============================] - 2s 56us/step - loss: 1.6510 - acc: 0.4722 - val_loss: 1.5350 - val_acc: 0.5564
Epoch 7/10
42000/42000 [==============================] - 2s 56us/step - loss: 1.5361 - acc: 0.5143 - val_loss: 1.4304 - val_ac

In [0]:
#Adding Batch normalizationa

model1=Sequential()
model1.add(keras.layers.Flatten(input_shape=(32,32,1)))
model1.add(Dense(200,activation ='relu'))
model1.add(Dense(100,activation ='relu'))
model1.add(Dense(50,activation ='relu'))
model1.add(keras.layers.normalization.BatchNormalization())
model1.add(Dense(10,activation='softmax'))

In [0]:
#Compile
model1.compile(loss='categorical_crossentropy',optimizer ='adam', metrics=['accuracy'])

In [21]:
model1.fit(x_train2,y_train, batch_size=64, epochs=10, 
              validation_data=(x_test2, y_test))

Train on 42000 samples, validate on 18000 samples
Epoch 1/10
42000/42000 [==============================] - 4s 104us/step - loss: 2.1484 - acc: 0.1894 - val_loss: 3.4760 - val_acc: 0.1788
Epoch 2/10
42000/42000 [==============================] - 4s 91us/step - loss: 1.6005 - acc: 0.4432 - val_loss: 1.4286 - val_acc: 0.5233
Epoch 3/10
42000/42000 [==============================] - 4s 89us/step - loss: 1.2493 - acc: 0.6006 - val_loss: 1.1805 - val_acc: 0.6306
Epoch 4/10
42000/42000 [==============================] - 4s 90us/step - loss: 1.1063 - acc: 0.6491 - val_loss: 1.0868 - val_acc: 0.6585
Epoch 5/10
42000/42000 [==============================] - 4s 87us/step - loss: 1.0138 - acc: 0.6825 - val_loss: 1.0141 - val_acc: 0.6858
Epoch 6/10
42000/42000 [==============================] - 4s 85us/step - loss: 0.9665 - acc: 0.6967 - val_loss: 0.9837 - val_acc: 0.6911
Epoch 7/10
42000/42000 [==============================] - 4s 85us/step - loss: 0.9311 - acc: 0.7069 - val_loss: 0.9189 - val_ac

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
y_pre=model1.predict(x_val2)

In [0]:
y_pre1=model1.predict(x_test2)

In [0]:
target_result=np.argmax(y_pre,axis=1)
test_result=np.argmax(y_pre1,axis=1)

In [30]:
#validation report
print(classification_report(y_val,target_result))
print(confusion_matrix(y_val,target_result))

ValueError: ignored